### ISSUE TITLE
可变参数方法hook不生效

### ISSUE THREAD

**Issue by Harlber** [PTrain666/JNIHook#1]
```java
#include <stdarg.h>


jint (*originCallStaticIntMethod)(JNIEnv *env,  jclass obj, jmethodID methodId, ...);
jint CallStaticIntMethodOverride(JNIEnv *env,  jclass javaclass, jmethodID methodId, ...) {
    LOG("hook success");
    va_list args;
    va_start(args, methodId);
    jint result = originCallStaticIntMethod(env, javaclass, methodId, args);
    va_end(args);
    return result;
}

void hookStaticIntMethod(JNIEnv *env) {
    auto *functionTable = env->functions;
    void** funcPointerAddress = (void **)&(functionTable->CallStaticIntMethod);
    accessWrite(reinterpret_cast<unsigned long>(funcPointerAddress));
    originCallStaticIntMethod = functionTable->CallStaticIntMethod;
    void** newFuncPointerAddress = reinterpret_cast<void **>(&CallStaticIntMethodOverride);
    *funcPointerAddress = newFuncPointerAddress;
}
```

可变参数方法hook未生效，普通方法没问题，也不报错，不知道什么原因导致

**Comment by PTrainbow** [comment]
不好意思，今天才看到，等周末看一下

**Comment by PTrainbow** [comment]
你也可以尝试直接 inlinehook

**Comment by PTrainbow** [comment]
> ```java
> #include <stdarg.h>
> 
> 
> jint (*originCallStaticIntMethod)(JNIEnv *env,  jclass obj, jmethodID methodId, ...);
> jint CallStaticIntMethodOverride(JNIEnv *env,  jclass javaclass, jmethodID methodId, ...) {
>    LOG("hook success");
>    va_list args;
>    va_start(args, methodId);
>    jint result = originCallStaticIntMethod(env, javaclass, methodId, args);
>    va_end(args);
>    return result;
> }
> 
> void hookStaticIntMethod(JNIEnv *env) {
>    auto *functionTable = env->functions;
>    void** funcPointerAddress = (void **)&(functionTable->CallStaticIntMethod);
>    accessWrite(reinterpret_cast<unsigned long>(funcPointerAddress));
>    originCallStaticIntMethod = functionTable->CallStaticIntMethod;
>    void** newFuncPointerAddress = reinterpret_cast<void **>(&CallStaticIntMethodOverride);
>    *funcPointerAddress = newFuncPointerAddress;
> }
> ```
> 
> 可变参数方法hook未生效，普通方法没问题，也不报错，不知道什么原因导致

可以看一下 https://github.com/PTrainbow/JNIHook/tree/dev/args 我这里的提交

可变参数需要指定的类型数组来接收参数，或者直接使用 void*

**Comment by Harlber** [comment]
- 我搜到的资料是用va_list去接收可变参数，这里只能用类型数据，大佬请指点一二
