### ISSUE TITLE
GC抑制Android10以后的适配方法

### ISSUE THREAD

**Issue by EansonLee** [PTrain666/JNIHook#2]
想请问一下之前的GC抑制的仓库还有吗，想学习一下

**Comment by PTrainbow** [comment]
> 想请问一下之前的GC抑制的仓库还有吗，想学习一下

和这个基本一致，但是 JIT 的可能会有 weak reference 的问题
https://github.com/RicardoJiang/android-performance/blob/main/startup-optimize/src/main/cpp/StartUpOptimize.cpp

**Comment by EansonLee** [comment]
如果在Android10上应该如何适配呢，还有其他各个机型，请问在线上验证过了吗






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年9月4日(星期三) 晚上6:21
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PTrainbow/JNIHook] GC抑制Android10以后的适配方法 (Issue #2)














  
想请问一下之前的GC抑制的仓库还有吗，想学习一下
  
和这个基本一致，但是 JIT 的可能会有 weak reference 的问题
 https://github.com/RicardoJiang/android-performance/blob/main/startup-optimize/src/main/cpp/StartUpOptimize.cpp

**Comment by PTrainbow** [comment]
> 如果在Android10上应该如何适配呢，还有其他各个机型，请问在线上验证过了吗
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2024年9月4日(星期三) 晚上6:21 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [PTrainbow/JNIHook] GC抑制Android10以后的适配方法 (Issue #2) 想请问一下之前的GC抑制的仓库还有吗，想学习一下 和这个基本一致，但是 JIT 的可能会有 weak reference 的问题 https://github.com/RicardoJiang/android-performance/blob/main/startup-optimize/src/main/cpp/StartUpOptimize.cpp — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

Android10 上系统已经有类似操作了。线上尝试过 收益不高

**Comment by EansonLee** [comment]
好的谢谢大佬解惑，那你们把这个功能移除掉了吗，还是有继续保留，虽然收益不高的情况下




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PTrainbow/JNIHook"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月5日(星期四) 下午2:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PTrainbow/JNIHook] GC抑制Android10以后的适配方法 (Issue #2)





  
如果在Android10上应该如何适配呢，还有其他各个机型，请问在线上验证过了吗
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2024年9月4日(星期三) 晚上6:21 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [PTrainbow/JNIHook] GC抑制Android10以后的适配方法 (Issue #2) 想请问一下之前的GC抑制的仓库还有吗，想学习一下 和这个基本一致，但是 JIT 的可能会有 weak reference 的问题 https://github.com/RicardoJiang/android-performance/blob/main/startup-optimize/src/main/cpp/StartUpOptimize.cpp — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
Android10 上系统已经有类似操作了。线上尝试过 收益不高

**Comment by PTrainbow** [comment]
> 好的谢谢大佬解惑，那你们把这个功能移除掉了吗，还是有继续保留，虽然收益不高的情况下
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "PTrainbow/JNIHook" ***@***.***&gt;; 发送时间:&nbsp;2024年9月5日(星期四) 下午2:52 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [PTrainbow/JNIHook] GC抑制Android10以后的适配方法 (Issue #2) 如果在Android10上应该如何适配呢，还有其他各个机型，请问在线上验证过了吗 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2024年9月4日(星期三) 晚上6:21 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [PTrainbow/JNIHook] GC抑制Android10以后的适配方法 (Issue #2) 想请问一下之前的GC抑制的仓库还有吗，想学习一下 和这个基本一致，但是 JIT 的可能会有 weak reference 的问题 https://github.com/RicardoJiang/android-performance/blob/main/startup-optimize/src/main/cpp/StartUpOptimize.cpp — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt; Android10 上系统已经有类似操作了。线上尝试过 收益不高 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

害！不是大佬。
功能是开的实验，收益没有很高，就关掉了。
但是，想继续卷的话，应该还是可以搞出些收益的，比如 提高各种阈值之类的。

**Comment by EansonLee** [comment]
明白，谢谢大佬，提供思路，我尝试把睡眠的阈值搞高一点，看看还有什么方面可以卷的
我看现在大佬的博客是今年来深圳了是吗


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PTrainbow/JNIHook"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月5日(星期四) 下午3:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PTrainbow/JNIHook] GC抑制Android10以后的适配方法 (Issue #2)





  
好的谢谢大佬解惑，那你们把这个功能移除掉了吗，还是有继续保留，虽然收益不高的情况下
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "PTrainbow/JNIHook" @.&gt;; 发送时间:&nbsp;2024年9月5日(星期四) 下午2:52 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [PTrainbow/JNIHook] GC抑制Android10以后的适配方法 (Issue #2) 如果在Android10上应该如何适配呢，还有其他各个机型，请问在线上验证过了吗 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2024年9月4日(星期三) 晚上6:21 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [PTrainbow/JNIHook] GC抑制Android10以后的适配方法 (Issue #2) 想请问一下之前的GC抑制的仓库还有吗，想学习一下 和这个基本一致，但是 JIT 的可能会有 weak reference 的问题 https://github.com/RicardoJiang/android-performance/blob/main/startup-optimize/src/main/cpp/StartUpOptimize.cpp — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&gt; Android10 上系统已经有类似操作了。线上尝试过 收益不高 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&gt;
  
害！不是大佬。
 功能是开的实验，收益没有很高，就关掉了。
 但是，想继续卷的话，应该还是可以搞出些收益的，比如 提高各种阈值之类的。

**Comment by PTrainbow** [comment]
> 明白，谢谢大佬，提供思路，我尝试把睡眠的阈值搞高一点，看看还有什么方面可以卷的 我看现在大佬的博客是今年来深圳了是吗
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "PTrainbow/JNIHook" ***@***.***&gt;; 发送时间:&nbsp;2024年9月5日(星期四) 下午3:45 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [PTrainbow/JNIHook] GC抑制Android10以后的适配方法 (Issue #2) 好的谢谢大佬解惑，那你们把这个功能移除掉了吗，还是有继续保留，虽然收益不高的情况下 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "PTrainbow/JNIHook" @.&gt;; 发送时间:&nbsp;2024年9月5日(星期四) 下午2:52 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [PTrainbow/JNIHook] GC抑制Android10以后的适配方法 (Issue #2) 如果在Android10上应该如何适配呢，还有其他各个机型，请问在线上验证过了吗 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2024年9月4日(星期三) 晚上6:21 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [PTrainbow/JNIHook] GC抑制Android10以后的适配方法 (Issue #2) 想请问一下之前的GC抑制的仓库还有吗，想学习一下 和这个基本一致，但是 JIT 的可能会有 weak reference 的问题 https://github.com/RicardoJiang/android-performance/blob/main/startup-optimize/src/main/cpp/StartUpOptimize.cpp — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&gt; Android10 上系统已经有类似操作了。线上尝试过 收益不高 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&gt; 害！不是大佬。 功能是开的实验，收益没有很高，就关掉了。 但是，想继续卷的话，应该还是可以搞出些收益的，比如 提高各种阈值之类的。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

😂来错地方了，正在跑路中···

**Comment by EansonLee** [comment]
哈哈哈，我看大佬也是干了很久了，准备换什么赛道吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PTrainbow/JNIHook"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月5日(星期四) 下午4:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PTrainbow/JNIHook] GC抑制Android10以后的适配方法 (Issue #2)





  
明白，谢谢大佬，提供思路，我尝试把睡眠的阈值搞高一点，看看还有什么方面可以卷的 我看现在大佬的博客是今年来深圳了是吗
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "PTrainbow/JNIHook" @.&gt;; 发送时间:&nbsp;2024年9月5日(星期四) 下午3:45 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [PTrainbow/JNIHook] GC抑制Android10以后的适配方法 (Issue #2) 好的谢谢大佬解惑，那你们把这个功能移除掉了吗，还是有继续保留，虽然收益不高的情况下 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "PTrainbow/JNIHook" @.&gt;; 发送时间:&nbsp;2024年9月5日(星期四) 下午2:52 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [PTrainbow/JNIHook] GC抑制Android10以后的适配方法 (Issue #2) 如果在Android10上应该如何适配呢，还有其他各个机型，请问在线上验证过了吗 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2024年9月4日(星期三) 晚上6:21 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [PTrainbow/JNIHook] GC抑制Android10以后的适配方法 (Issue #2) 想请问一下之前的GC抑制的仓库还有吗，想学习一下 和这个基本一致，但是 JIT 的可能会有 weak reference 的问题 https://github.com/RicardoJiang/android-performance/blob/main/startup-optimize/src/main/cpp/StartUpOptimize.cpp — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&gt; Android10 上系统已经有类似操作了。线上尝试过 收益不高 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&gt; 害！不是大佬。 功能是开的实验，收益没有很高，就关掉了。 但是，想继续卷的话，应该还是可以搞出些收益的，比如 提高各种阈值之类的。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
😂来错地方了，正在跑路中···

**Comment by PTrainbow** [comment]
> 哈哈哈，我看大佬也是干了很久了，准备换什么赛道吗
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "PTrainbow/JNIHook" ***@***.***&gt;; 发送时间:&nbsp;2024年9月5日(星期四) 下午4:29 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [PTrainbow/JNIHook] GC抑制Android10以后的适配方法 (Issue #2) 明白，谢谢大佬，提供思路，我尝试把睡眠的阈值搞高一点，看看还有什么方面可以卷的 我看现在大佬的博客是今年来深圳了是吗 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "PTrainbow/JNIHook" @.&gt;; 发送时间:&nbsp;2024年9月5日(星期四) 下午3:45 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [PTrainbow/JNIHook] GC抑制Android10以后的适配方法 (Issue #2) 好的谢谢大佬解惑，那你们把这个功能移除掉了吗，还是有继续保留，虽然收益不高的情况下 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "PTrainbow/JNIHook" @.&gt;; 发送时间:&nbsp;2024年9月5日(星期四) 下午2:52 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [PTrainbow/JNIHook] GC抑制Android10以后的适配方法 (Issue #2) 如果在Android10上应该如何适配呢，还有其他各个机型，请问在线上验证过了吗 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2024年9月4日(星期三) 晚上6:21 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [PTrainbow/JNIHook] GC抑制Android10以后的适配方法 (Issue #2) 想请问一下之前的GC抑制的仓库还有吗，想学习一下 和这个基本一致，但是 JIT 的可能会有 weak reference 的问题 https://github.com/RicardoJiang/android-performance/blob/main/startup-optimize/src/main/cpp/StartUpOptimize.cpp — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&gt; Android10 上系统已经有类似操作了。线上尝试过 收益不高 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&gt; 害！不是大佬。 功能是开的实验，收益没有很高，就关掉了。 但是，想继续卷的话，应该还是可以搞出些收益的，比如 提高各种阈值之类的。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt; 😂来错地方了，正在跑路中··· — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

铁人三项，外卖/滴滴/快递，哈哈哈

**Comment by EansonLee** [comment]
哈哈哈，有机会带带我


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PTrainbow/JNIHook"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月5日(星期四) 下午5:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PTrainbow/JNIHook] GC抑制Android10以后的适配方法 (Issue #2)





  
哈哈哈，我看大佬也是干了很久了，准备换什么赛道吗
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "PTrainbow/JNIHook" @.&gt;; 发送时间:&nbsp;2024年9月5日(星期四) 下午4:29 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [PTrainbow/JNIHook] GC抑制Android10以后的适配方法 (Issue #2) 明白，谢谢大佬，提供思路，我尝试把睡眠的阈值搞高一点，看看还有什么方面可以卷的 我看现在大佬的博客是今年来深圳了是吗 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "PTrainbow/JNIHook" @.&gt;; 发送时间:&nbsp;2024年9月5日(星期四) 下午3:45 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [PTrainbow/JNIHook] GC抑制Android10以后的适配方法 (Issue #2) 好的谢谢大佬解惑，那你们把这个功能移除掉了吗，还是有继续保留，虽然收益不高的情况下 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "PTrainbow/JNIHook" @.&gt;; 发送时间:&nbsp;2024年9月5日(星期四) 下午2:52 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [PTrainbow/JNIHook] GC抑制Android10以后的适配方法 (Issue #2) 如果在Android10上应该如何适配呢，还有其他各个机型，请问在线上验证过了吗 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2024年9月4日(星期三) 晚上6:21 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [PTrainbow/JNIHook] GC抑制Android10以后的适配方法 (Issue #2) 想请问一下之前的GC抑制的仓库还有吗，想学习一下 和这个基本一致，但是 JIT 的可能会有 weak reference 的问题 https://github.com/RicardoJiang/android-performance/blob/main/startup-optimize/src/main/cpp/StartUpOptimize.cpp — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&gt; Android10 上系统已经有类似操作了。线上尝试过 收益不高 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&gt; 害！不是大佬。 功能是开的实验，收益没有很高，就关掉了。 但是，想继续卷的话，应该还是可以搞出些收益的，比如 提高各种阈值之类的。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&gt; 😂来错地方了，正在跑路中··· — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&gt;
  
铁人三项，外卖/滴滴/快递，哈哈哈
